### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by laitr01** [cpinan/Cocos2dX_GooglePlayGamesServices#10]
when i compiled this error happen
In file included from jni/hellocpp/main.cpp:1:0:
jni/../../Classes/AppDelegate.h:12:27: fatal error: CCApplication.h: No such file or directory

please give me any idea to fix it

**Comment by OscarLeif** [comment]
This project is old maybe you should switch to Cocos-Helper 
https://github.com/SonarSystems/Cocos-Helper

**Comment by spacolino** [comment]
This is old, use sdkbox instead. http://www.cocos2d-x.org/sdkbox

**Comment by cpinan** [comment]
They are rigth. This project is too old use sdkbox.
