### ISSUE TITLE
Screen flickering on login

### ISSUE THREAD

**Issue by hydex86** [cpinan/Cocos2dX_GooglePlayGamesServices#4]
I integrated your code and everything works fine (thank you for your great job). The only problem I've been experiencing: the screen blinks when my Android app is logging into Google Play Game Services. 

I've seen here (http://www.cocos2d-x.org/forums/6/topics/49532?r=50787#message-50787) you made a fix for a related issue, but I cloned your repo a week ago (so I think I've the patch for this issue). 

Here you can see a video with the flicking effect. Do you know what could be happening? Or something to check?

http://youtu.be/66GlOosaRVI

**Comment by cpinan** [comment]
Hi Daniel. Wow it is rarely. Let me see the flickering because I follow
some instructions from other developer because is a bug on cocos2d-x when
load another activity.

Could you send me the code from "Cocos2dxActivity.java"? Just to check

2014-05-09 10:26 GMT-05:00 Daniel Albert notifications@github.com:

> I integrated your library and everything works fine (thank you for your
> great job). The only problem I've been experiencing: the screen blinks when
> my Android app is logging in into Google Play Game Services.
> 
> I've seen here (
> http://www.cocos2d-x.org/forums/6/topics/49532?r=50787#message-50787) you
> made a fix for a related issue, but I cloned your repo a week ago (so I
> think I've the patch for this issue).
> 
> Here you can see a video with the flicking effect. Do you know what could
> be happening? Or something to check?
> 
> http://youtu.be/66GlOosaRVI
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cpinan/Cocos2dX_GooglePlayGamesServices/issues/4
> .

## 

Atentamente,

Carlos Eduardo Piñán Indacochea.

Ingeniero de Sistemas
Especializado en Gestión, Análisis y Desarrollo.

**Comment by hydex86** [comment]
I didn't modify this class. I use the original from cocos2d-x.2.2.2. Did you apply the patch to this class? This is my "Cocos2dxActivity.java".

https://db.tt/bhlXpijY

Thank you!

**Comment by cpinan** [comment]
Sorry mi mistake the file is "Cocos2dxGLSurfaceView.java" Currently I have
a game that use that configuration

Here is the code of that class:

https://github.com/cpinan/Cocos2dX_GooglePlayGamesServices/blob/master/GooglePlayGameServices/proj.android/src/org/cocos2dx/lib/Cocos2dxGLSurfaceView.java

And here is my game:
https://play.google.com/store/apps/details?id=com.carlospinan.turborace

It's rarely the flickering but I will check my code again tonight when I
will be on my home.

Please check that java file and I'm still finding about that issue.

2014-05-09 10:53 GMT-05:00 Daniel Albert notifications@github.com:

> I didn't modify this class. I use the original from cocos2d-x.2.2.2. Did
> you apply the patch to this class? This is my "Cocos2dxActivity.java".
> 
> https://db.tt/bhlXpijY
> 
> Thank you!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cpinan/Cocos2dX_GooglePlayGamesServices/issues/4#issuecomment-42681594
> .

## 

Atentamente,

Carlos Eduardo Piñán Indacochea.

Ingeniero de Sistemas
Especializado en Gestión, Análisis y Desarrollo.

**Comment by hydex86** [comment]
Ok I see, this could be the key:

this.setRenderMode(RENDERMODE_CONTINUOUSLY); 

I'll try it tonight too ;) Thank you!

**Comment by hydex86** [comment]
It worked, thanks!!

**Comment by cpinan** [comment]
Eh! =D Nice

2014-05-09 12:49 GMT-05:00 Daniel Albert notifications@github.com:

> Closed #4https://github.com/cpinan/Cocos2dX_GooglePlayGamesServices/issues/4
> .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cpinan/Cocos2dX_GooglePlayGamesServices/issues/4#event-119644257
> .

## 

Atentamente,

Carlos Eduardo Piñán Indacochea.

Ingeniero de Sistemas
Especializado en Gestión, Análisis y Desarrollo.
